
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 18:13:55 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CONST = 12;
  public static final int GE = 40;
  public static final int CASE = 24;
  public static final int SEMI = 49;
  public static final int LPAREN = 7;
  public static final int CONTINUE = 21;
  public static final int FOR = 19;
  public static final int MINUS = 33;
  public static final int CHARACTER = 47;
  public static final int RPAREN = 8;
  public static final int AND = 31;
  public static final int LT = 41;
  public static final int OR = 30;
  public static final int BOOL = 48;
  public static final int COMMA = 5;
  public static final int INC = 27;
  public static final int DIV = 35;
  public static final int PLUS = 32;
  public static final int ASSIGN = 26;
  public static final int IF = 17;
  public static final int DOT = 6;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int RBRACKET = 10;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int NUMBER = 45;
  public static final int MOD = 36;
  public static final int IDENT = 46;
  public static final int BREAK = 20;
  public static final int VOID = 11;
  public static final int EQ = 37;
  public static final int SWITCH = 23;
  public static final int COLON = 25;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int READ = 43;
  public static final int ENUM = 13;
  public static final int WHILE = 16;
  public static final int RBRACE = 4;
  public static final int NE = 38;
  public static final int PROG = 2;
  public static final int QUESTION = 29;
  public static final int DEC = 28;
  public static final int GT = 39;
  public static final int PRINT = 44;
  public static final int LENGTH = 15;
}

